b'Traceback (most recent call last):\r\n  File "C:\\Users\\palac\\Documents\\DHBW\\Studienarbeit\\lecture_examples_python\\Python\\Testing\\..\\from.py", line 14, in <module>\r\n    printSet(s)\r\n  File "C:\\Users\\palac\\Documents\\DHBW\\Studienarbeit\\lecture_examples_python\\Python\\Testing\\..\\from.py", line 9, in printSet\r\n    x = s.pop()\r\n  File "C:\\Users\\palac\\Documents\\DHBW\\Studienarbeit\\lecture_examples_python\\Python\\lecture\\set.py", line 104, in pop\r\n    return self.data.pop(random.randrange(len(self.data)))\r\nAttributeError: \'Set\' object has no attribute \'data\'\r\n'